---
title: "eQTL Website"
---


```{r init, include=FALSE}
library(tidyverse)
# import package to allow R data objects to be displayed as tables on HTML pages
library(DT)
```


## Regular Gene-SNP table

```{r include=FALSE}
# init. filepath
path_to_genes <- "website/data/plots/"
# init. genes names to store in DF
genes <- list.files(path_to_genes)

# init. DF with gene and SNP combos
df <- tibble(
  gene = NA,
  snp = NA
)

for (gene in genes) {
  # init. vector of SNPs for each gene
  snps <- list.files(str_c(path_to_genes, gene))
  
  # init. temporary DF to store each gene-SNP combination
  temp_df <- tibble(gene = gene, snp = snps)
  
  # bind DF with temporary DF
  df <- bind_rows(df, temp_df)
}

df <- df %>% filter(!is.na(gene))

# df <- df %>%
#   filter(!is.na(gene)) %>%
#   datatable(escape = F, style = "auto")
```



```{r display table, echo=FALSE, include=FALSE}
df_html <- df %>%
  datatable(escape = F, style = "auto")

df_html
```


---

## Feature-Selected Model: Phenotype Rank-Normalized CPM


```{r include=FALSE}
# read in feature selected rank-normalized CPM model
fs_rank_norm_cpm <- read_tsv("website/data/modeling_results/modeling_results_featureSelectedModel_phenotypeRankNormCPM.txt")


fs_rank_norm_cpm <- fs_rank_norm_cpm %>%
  left_join(
    df,
    by = c("GENE" = "gene", "SNP" = "snp")
  )
```


```{r echo=FALSE, warning=FALSE, message=FALSE}
# init. URL base
url_gene_base <- "https://www.genecards.org/cgi-bin/carddisp.pl?gene="
url_snp_base <- "https://www.ncbi.nlm.nih.gov/snp/"

fs_rank_norm_cpm %>%
  mutate(
    GENE = str_c("<a href=", url_gene_base, GENE, " target=_blank", ">", GENE, "</a>"),
    SNP = str_c("<a href=", url_snp_base, SNP, " target=_blank", ">", SNP, "</a>")
  ) %>%
  datatable(escape = F, style = "auto")
```




---


## Feature-Selected Model: Phenotype CPM

```{r feature_selected_models, include=FALSE, eval=FALSE}
# read in different modeling results as tables
feat_select_CPM <- read_tsv("website/data/modeling_results/modeling_results_featureSelectedModel_phenotypeCPM.txt")

feat_select_CPM <- feat_select_CPM %>%
  left_join(
    df,
    by = c("GENE" = "gene", "SNP" = "snp")
  )
```


```{r include=FALSE, eval=FALSE}
# init. URL base
url_gene_base <- "https://www.ncbi.nlm.nih.gov/gene/?term="
url_snp_base <- "https://www.ncbi.nlm.nih.gov/snp/"

feat_select_CPM %>%
  mutate(
    GENE = str_c("<a href=", url_gene_base, GENE, " target=_blank", ">", GENE, "</a>"),
    SNP = str_c("<a href=", url_snp_base, SNP, " target=_blank", ">", SNP, "</a>")
  ) %>%
  datatable(escape = F, style = "auto")
```





